# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  schedule:
    - cron:  '42 16 * * *'
    # This runs at 10:00 AM UTC each day.
    # * is a special character in YAML so you have to quote this string
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'test'
      tags:
        description: 'Test scenario tags'  
permissions:
  contents: read
jobs:
  build:

    runs-on: ubuntu-latest
    env:
        ELEMENTS_EMAIL: ${{ secrets.ELEMENTS_EMAIL }}
        ELEMENTS_PASSWORD: ${{ secrets.ELEMENTS_PASSWORD }}
        ELEMENTS_STUDIOS: ${{ secrets.ELEMENTS_STUDIOS }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: generate with Maven
      run: mvn -B package --file pom.xml
    - name: run main from jar
      run: java -cp /home/runner/work/elements-wellpass-registration/elements-wellpass-registration/target/elements-wellpass-registration-1.0.jar ElementsAutomation
     
  
